import 'package:flutter/widgets.dart';

// Generated by tool/subset_icons.py: do not edit.
// ignore_for_file: constant_identifier_names
abstract final class UhfIcons {
  static const IconData add = IconData(0xe145, fontFamily: 'UhfIcons');
  static const IconData audiotrack = IconData(0xe405, fontFamily: 'UhfIcons');
  static const IconData check = IconData(0xe668, fontFamily: 'UhfIcons');
  static const IconData close = IconData(0xe5cd, fontFamily: 'UhfIcons');
  static const IconData content_cut = IconData(0xe14e, fontFamily: 'UhfIcons');
  static const IconData crop = IconData(0xe3be, fontFamily: 'UhfIcons');
  static const IconData folder_open = IconData(0xe2c8, fontFamily: 'UhfIcons');
  static const IconData fullscreen = IconData(0xe5d0, fontFamily: 'UhfIcons');
  static const IconData fullscreen_exit = IconData(0xe5d1, fontFamily: 'UhfIcons');
  static const IconData more_horiz = IconData(0xe5d3, fontFamily: 'UhfIcons');
  static const IconData movie_edit = IconData(0xf840, fontFamily: 'UhfIcons');
  static const IconData pause = IconData(0xe034, fontFamily: 'UhfIcons');
  static const IconData play_arrow = IconData(0xe037, fontFamily: 'UhfIcons');
  static const IconData push_pin = IconData(0xf10d, fontFamily: 'UhfIcons');
  static const IconData remove = IconData(0xe15b, fontFamily: 'UhfIcons');
  static const IconData subtitles = IconData(0xe048, fontFamily: 'UhfIcons');
  static const IconData volume_off = IconData(0xe04f, fontFamily: 'UhfIcons');
  static const IconData volume_up = IconData(0xe050, fontFamily: 'UhfIcons');
  static const IconData replay_10 = IconData(0xe059, fontFamily: 'UhfIcons');
  static const IconData forward_10 = IconData(0xe056, fontFamily: 'UhfIcons');
  static const IconData music_note = IconData(0xe405, fontFamily: 'UhfIcons');
}
