"""Builds assets/fonts/UhfIcons.ttf and lib/ui/icons.dart from the icon names below.

The material_symbols_icons package ships three 9-15 MB fonts; the app only needs a
handful of glyphs. Add a name to ICONS (a Material Symbols name without style suffix),
run `python tool/subset_icons.py`, and use `UhfIcons.<name>`.
"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

STYLE = 'sharp'  # sharp | rounded | outlined
ICONS = [
    'add', 'audiotrack', 'check', 'close', 'content_cut', 'crop', 'folder_open',
    'fullscreen', 'fullscreen_exit', 'more_horiz', 'movie_edit', 'pause',
    'play_arrow', 'push_pin', 'remove', 'subtitles', 'volume_off', 'volume_up',
    'replay_10', 'forward_10', 'music_note',
]

root = Path(__file__).resolve().parent.parent
config = json.loads((root / '.dart_tool' / 'package_config.json').read_text('utf-8'))
entry = next(p for p in config['packages'] if p['name'] == 'material_symbols_icons')
uri = entry['rootUri']
if uri.startswith('file:'):
    pkg = Path(unquote(urlparse(uri).path.lstrip('/')))
else:
    pkg = (root / '.dart_tool' / uri).resolve()

symbols = (pkg / 'lib' / 'symbols.dart').read_text('utf-8')
codepoints = {}
for name in ICONS:
    m = re.search(rf'static const IconData {name}_{STYLE} =\s*IconData\(0x([0-9a-f]+),', symbols)
    if not m:
        sys.exit(f'unknown icon: {name}_{STYLE}')
    codepoints[name] = int(m.group(1), 16)

font = TTFont(pkg / 'lib' / 'fonts' / f'MaterialSymbols{STYLE.capitalize()}.ttf')
# Pin the variable axes (FILL 0, GRAD 0, opsz 24, wght 400) so only one master is kept.
font = instancer.instantiateVariableFont(font, {'FILL': 0, 'GRAD': 0, 'opsz': 24, 'wght': 400})
opts = subset.Options()
opts.layout_features = []
opts.glyph_names = False
opts.notdef_outline = True
opts.name_IDs = [1, 2]
sub = subset.Subsetter(opts)
sub.populate(unicodes=list(codepoints.values()))
sub.subset(font)
out = root / 'assets' / 'fonts' / 'UhfIcons.ttf'
font.save(out)

lines = [
    "import 'package:flutter/widgets.dart';",
    '',
    '// Generated by tool/subset_icons.py: do not edit.',
    '// ignore_for_file: constant_identifier_names',
    'abstract final class UhfIcons {',
]
for name, cp in codepoints.items():
    lines.append(f"  static const IconData {name} = IconData(0x{cp:x}, fontFamily: 'UhfIcons');")
lines.append('}')
(root / 'lib' / 'ui' / 'icons.dart').write_text('\n'.join(lines) + '\n', 'utf-8')
print(f'{out.name}: {out.stat().st_size} bytes, {len(codepoints)} icons')
